spring:
  application:
    name: transaction-service
    bad_request: 400
    conflict: 409
    ok: 200

  spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8084